# Generated by Django 3.0.4 on 2020-03-25 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recomendador', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calificacion',
            old_name='producto',
            new_name='asignatura',
        ),
    ]
